config/routes.rb
InvestBrasil::Application.routes.draw do
  root :to => 'home#index'  
  
  # TO-DO
  # ALTERAR NO DEVELOPERS.FACEBOOK.COM 
  # A ROTA DE LOCALHOST:3000 QUANDO SISTEMA FOR PRO AR

  match 'auth/:provider/callback', to: 'sessions#create_with_facebook'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :companies

  match 'companies/:company_id/create_comment', to: 'companies#create_comment', as: 'create_comment'
  match 'companies/:company_id/:comment_id/create_subcomment', to: 'companies#create_subcomment', as: 'create_subcomment'
  match 'companies/:company_id/:comment_id/create_subcomment_in_notifications', to: 'companies#create_subcomment_in_notifications', 
                                                                      as: 'create_subcomment_in_notifications'
  match 'companies/:company_id/:comment_id/create_subcomment_in_home', to: 'companies#create_subcomment_in_home', 
                                                                      as: 'create_subcomment_in_home'
                                                                    
  match 'companies/:company_id/follow_company', to: 'users#follow_company', as: 'follow_company'
  match 'companies/:company_id/unfollow_company', to: 'users#unfollow_company', as: 'unfollow_company'

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'  
  
  resources :users
  resources :sessions
  resources :notifications

  match "/companies_ajax" => "companies#companies_ajax"
  match "/redirect_to_correct_company" => "companies#redirect_to_correct_company",
                                :as => 'redirect_to_correct_company'

  match "companies/sector/:sector_id" => "sectors#show", :as => 'sectors'                         
  match "companies/subsector/:subsector_id" => "subsectors#show", :as => 'subsectors'                         
  match "companies/segment/:segment_id" => "segments#show", :as => 'segments'                         

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

	def index
		if current_user
			@notifications = current_user.notifications	
		end
	end

	def show
		@notification = Notification.find params[:id]
		@notification.read = true
		@notification.save
		@comment = Comment.find @notification.comment_id

		company_user = CompanyUser.find @comment.company_user_id
		company_id = company_user.company_id
		@company = Company.find company_id	
	end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<% if current_user %>	
	<% @notifications.each do |notification| %>
	  <% comment = Comment.find(notification.comment_id) %>
		<div class="well">
			<h3>
				<% if notification.read %>
					<span class="label label-success">Lido</span>
				<% else %>
					<span class="label label-warning">Não lido</span>
				<% end %>
				<%= image_tag comment.user.avatar.url(:thumb) %>
				<%= comment.owner %>: <%= link_to comment.content, notification_path(notification) %>
			</h3>
		</div>	
	<% end %>
<% else %>
	<h3>Você precisa estar cadastrado para ter notificações</h3>
<% end %>

app/views/notifications/show.html.erb
<%= javascript_include_tag 'subcomment' %>

<h2><%= link_to @company.name, company_path(@company) %></h2>

<div id="comments">
	<div class="well">
		<h3>
			<%= image_tag @comment.user.avatar.url(:thumb) %>
			<%= link_to @comment.owner %>: <%= @comment.content %>
		</h3>
		<p class="timestamp">
	    Postado <%= time_ago_in_words(@comment.created_at) %> atrás.
	  </p>
	  <hr>
		<ul>
			<% @comment.subcomments.each do |subcomment| %>
		  <span class="content">
		  	<%= image_tag subcomment.user.avatar.url(:thumb) %>
		  	<%= link_to subcomment.owner %>: <%= subcomment.content %>
		  </span>
		  <p class="timestamp">
		    Postado <%= time_ago_in_words(subcomment.created_at) %> atrás.
		  </p>
		<% end %>

		<% if current_user %>
			<%= form_tag(create_subcomment_in_notifications_path @company, @comment, :method => :post) do %>
	  	<div class="field subcomment"><%= text_area_tag 'content', '', :rows => "1", :placeholder => 'Entre com seu comentário' %></div>
	  		<button type="submit" value="post" class="btn btn-inverse">
	  			<i class="icon-comment"></i> Comentar
				</button>
			<% end %>
		<% end %>
		</ul>
	</div>
</div>