config/routes.rb
InvestBrasil::Application.routes.draw do
  root :to => 'home#index'  
  
  # TO-DO
  # ALTERAR NO DEVELOPERS.FACEBOOK.COM 
  # A ROTA DE LOCALHOST:3000 QUANDO SISTEMA FOR PRO AR

  match 'auth/:provider/callback', to: 'sessions#create_with_facebook'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :companies

  match 'companies/:company_id/create_comment', to: 'companies#create_comment', as: 'create_comment'
  match 'companies/:company_id/:comment_id/create_subcomment', to: 'companies#create_subcomment', as: 'create_subcomment'
  match 'companies/:company_id/:comment_id/create_subcomment_in_notifications', to: 'companies#create_subcomment_in_notifications', 
                                                                      as: 'create_subcomment_in_notifications'
  match 'companies/:company_id/:comment_id/create_subcomment_in_home', to: 'companies#create_subcomment_in_home', 
                                                                      as: 'create_subcomment_in_home'
                                                                    
  match 'companies/:company_id/follow_company', to: 'users#follow_company', as: 'follow_company'
  match 'companies/:company_id/unfollow_company', to: 'users#unfollow_company', as: 'unfollow_company'

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'  
  
  resources :users
  resources :sessions
  resources :notifications

  match "/companies_ajax" => "companies#companies_ajax"
  match "/redirect_to_correct_company" => "companies#redirect_to_correct_company",
                                :as => 'redirect_to_correct_company'

  match "companies/sector/:sector_id" => "sectors#show", :as => 'sectors'                         
  match "companies/subsector/:subsector_id" => "subsectors#show", :as => 'subsectors'                         
  match "companies/segment/:segment_id" => "segments#show", :as => 'segments'                         

end

app/models/company.rb
class Company < ActiveRecord::Base
	attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "150x150>", :thumb => "32x32>" }
	has_many :company_users
	belongs_to :segment
	belongs_to :sector
	belongs_to :subsector
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def index
		@companies = Company.all
	end

	def show
		@company = Company.find params[:id]
		@comments = company_comments(@company.id).paginate(:page => params[:page], :per_page => 5)		
	end

	def new
		if current_user && current_user.admin?
			@company = Company.new
		else
			redirect_to companies_path
		end
	end

	def create
		@company = Company.new params[:company]
		
		if @company.save
			redirect_to companies_path, :notice => 'Empresa criada com sucesso'			
		else
			render 'new'
		end
	end

	def edit
		if current_user && current_user.admin?
			@company = Company.find params[:id]
		else
			redirect_to companies_path
		end
	end

	def update
		if current_user && current_user.admin?
			@company = Company.find params[:id]
			
			if @company.update_attributes params[:company]
				redirect_to companies_path, :notice => 'Empresa atualizada com sucesso'			
			else
				render 'edit'
			end
		else
			redirect_to companies_path
		end
	end

	def destroy
		if current_user && current_user.admin?
			company = Company.find params[:id]
			company.destroy

			redirect_to companies_path, :notice => 'Empresa deletada com sucesso'
		else
			redirect_to companies_path
		end
	end

	def create_comment
		company_user = CompanyUser.where(:company_id => params[:company_id],
																		 :user_id => session[:user_id])

		if company_user.blank?																	
			company_user = CompanyUser.create :company_id => params[:company_id],
																				:user_id => session[:user_id]
		else
			company_user = company_user.first																		
		end

		comment = Comment.create :content => params[:content],
														 :company_user_id => company_user.id,
														 :user_id => session[:user_id]

		redirect_to company_path params[:company_id]												 
	end

	def create_subcomment
		subcomment = Subcomment.create :content => params[:content],
																	 :comment_id => params[:comment_id],
																	 :user_id => session[:user_id]
		comment = Comment.find params[:comment_id]
		comment.update_attributes :updated_at => Time.zone.now

		users = []
		users << comment.user
		comment.subcomments.each do |subcomment|
			users << subcomment.user unless users.include? subcomment.user
		end

		users.each do |user|
			notification = Notification.where(:comment_id => comment.id, :user_id => user.id)
			if notification.present?
		  	notification.first.update_attributes :read => nil
		  else
		  	Notification.create :comment_id => comment.id, :user_id => user.id
			end
		end

		redirect_to company_path params[:company_id]
	end

	def create_subcomment_in_notifications
		subcomment = Subcomment.create :content => params[:content],
																	 :comment_id => params[:comment_id],
																	 :user_id => session[:user_id]
		comment = Comment.find params[:comment_id]
		comment.update_attributes :updated_at => Time.zone.now

		users = []
		users << comment.user
		comment.subcomments.each do |subcomment|
			users << subcomment.user unless users.include? subcomment.user
		end

		users.each do |user|
			notification = Notification.where(:comment_id => comment.id, :user_id => user.id)
			if notification.present?
				notification = notification.first
		  	notification.update_attributes :read => nil
		  else
		  	notification = Notification.create :comment_id => comment.id, :user_id => user.id
			end
			redirect_to notification_path(notification)
		end
	end

	def create_subcomment_in_home
		subcomment = Subcomment.create :content => params[:content],
																	 :comment_id => params[:comment_id],
																	 :user_id => session[:user_id]
		comment = Comment.find params[:comment_id]
		comment.update_attributes :updated_at => Time.zone.now

		users = []
		users << comment.user
		comment.subcomments.each do |subcomment|
			users << subcomment.user unless users.include? subcomment.user
		end

		users.each do |user|
			notification = Notification.where(:comment_id => comment.id, :user_id => user.id)
			if notification.present?
				notification = notification.first
		  	notification.update_attributes :read => nil
		  else
		  	notification = Notification.create :comment_id => comment.id, :user_id => user.id
			end
			redirect_to root_url
		end
	end

	def companies_ajax
		if params[:term]
      like = "%".concat(params[:term].concat("%"))
      companies = Company.where("name like ?", like)
    else
      companies = Company.all
    end
    list = companies.map {|u| Hash[ id: u.id, label: u.name, name: u.name]}
    render json: list
	end

	def redirect_to_correct_company
		company = Company.find_by_name params[:company]
		if company
			redirect_to company_path company
		else
			redirect_to companies_path
		end
	end

	private

	def company_comments company_id
		company_user = CompanyUser.where :company_id => company_id
		comments = []

		unless company_user.blank?
			company_user.each do |c|
				c.comments.each do |comment|
					comments << comment 
				end
			end
		end

		comments.sort_by{|c| c[:updated_at]}.reverse
	end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_comments.html.erb
<% comments.each do |comment| %>
	<div class="well">
		<h3>
			<%= image_tag comment.user.avatar.url(:thumb) %>
			<%= link_to comment.owner %>: <%= comment.content %>
		</h3>
		<p class="timestamp">
	    Postado <%= time_ago_in_words(comment.created_at) %> atrás.
	  </p>
	  <hr>
		<ul>
			<%= render :partial => 'subcomments', :locals => {:comment => comment} %>
			<%= render :partial => 'create_subcomment', :locals => {:comment => comment, :company => company} %>
		</ul>
	</div>
	<hr>
<% end %>

app/views/companies/_comments_manager.html.erb
<%= render :partial => 'comments', :locals => {:comments => comments, :company => company} unless comments.blank? %>

app/views/companies/_companies.html.erb
<table class="table table-striped">
	<tbody>
		<% companies.each do |company| %>
			<tr>
				<td><%= link_to company.name, company %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/companies/_company_info.html.erb
<h2>
<% if company.avatar_file_name %>
	<%= image_tag company.avatar.url(:thumb) %>
<% end %>
	<%= company.name %>
	<% if current_user %> 
		<% if current_user.is_following_company? company.id %>
			<%= link_to 'Deixar de seguir', unfollow_company_path(company), :class => 'btn btn-danger' %>
		<% else %>
			<%= link_to 'Seguir', follow_company_path(company), :class => 'btn btn-primary' %>
		<% end %>
	<% end %>
</h2>
<ul>
	<li>Atividade: <%= company.activity %></li>
	<li>Setor:
	<% if company.sector %> 
		<%= link_to company.sector.name, sectors_path(company.sector.id) %></li>
	<% end %>	
	<li>Sub-Setor: 
	<% if company.subsector %> 
		<%= link_to company.subsector.name, subsectors_path(company.subsector.id) %></li>
	<% end %>
	<li>Segmento de Mercado: 
	<% if company.segment %> 
		<%= link_to company.segment.name, segments_path(company.segment.id) %></li>
	<% end %>
	<li>Segmento de Listagem: <%= company.listing_segment %></li>
	<li>Valor de Mercado: <%= company.market_value %></li>
	<li>Site: <%= link_to company.website, company.website %></li>
</ul>

app/views/companies/_create_comment.html.erb
<%= form_tag(create_comment_path company, :method => :post) do %>
  <div class="field"><%= text_area_tag 'content', '', {:rows => 3, :placeholder => placeholder_condition(current_user), :disabled => disabled_if_no_user(current_user) } %></div>
	<button type="submit" value="post" class="btn btn-inverse" <%= disabled?(current_user) %>>
  	<i class="icon-comment"></i> Comentar
	</button>
<% end %>

app/views/companies/_create_subcomment.html.erb
<%= javascript_include_tag 'subcomment' %>

<%= form_tag(create_subcomment_path company, comment, :method => :post) do %>
  <div class="field subcomment"><%= text_area_tag 'content', '', {:rows => 1, :placeholder => placeholder_condition(current_user), :disabled => disabled_if_no_user(current_user) } %></div>
  <button type="submit" value="post" class="btn btn-inverse" <%= disabled?(current_user) %>>
  	<i class="icon-comment"></i> Comentar
	</button>
<% end %>

app/views/companies/_form.html.erb
<%= form_for company do |f| %>
  <% if company.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in company.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :nome %>
  <%= f.text_field :name, :class => 'default' %>

  <div>       
    <%= f.submit :class => 'btblue btlarge', :value => "Salvar" %>
  </div>

<% end %>

app/views/companies/_subcomments.html.erb
<% comment.subcomments.each do |subcomment| %>
  <span class="content">
  	<%= image_tag subcomment.user.avatar.url(:thumb) %>
  	<%= link_to subcomment.owner %>: <%= subcomment.content %>
  </span>
  <p class="timestamp">
    Postado <%= time_ago_in_words(subcomment.created_at) %> atrás.
  </p>
<% end %>

app/views/companies/edit.html.erb
<h1>Editar empresa</h1>
<%= render :partial => 'form', :locals => {:company => @company} %>

app/views/companies/index.html.erb
<% if current_user && current_user.admin? %>
	<%= link_to 'Criar nova empresa', new_company_path %>
<% end %>	

<h1>Empresas</h1>
<%= render :partial => 'companies', :locals => {:companies => @companies} %>

app/views/companies/new.html.erb
<h1>Criar nova empresa</h1>
<%= render :partial => 'form', :locals => {:company => @company} %>

app/views/companies/show.html.erb
<%= javascript_include_tag 'comments' %>

<% if current_user && current_user.admin? %>
	<%= link_to 'Editar empresa', edit_company_path(@company) %>
	<%= link_to 'Deletar empresa', @company, :method => :delete, :confirm => 'Confirma?' %>
	<%= form_for @company, :html => { :multipart => true } do |form| %>
  	<%= form.file_field :avatar %>
  	<%= form.submit :value => "Salvar" %>
	<% end %>
<% end %>

<div class="page-header">
	<%= render :partial => 'company_info', :locals => {:company => @company} %>
</div>

<h3>Comentários</h3>
<%= render :partial => 'create_comment', :locals => {:company => @company} %>
<hr>

<div id="comments">
	<%= render :partial => 'comments_manager', :locals => {:comments => @comments, :company => @company} %>
</div>

<%= will_paginate @comments, :previous_label => "&nbsp; &laquo; Anterior", :next_label => "&nbsp; Próxima &raquo;" %>

app/views/companies/show.js.erb
$('#comments').append('<%= j render :partial => 'comments_manager', :locals => {:comments => @comments, :company => @company} %>');
<% if @comments.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@comments) %>');
<% else %>
  $('.pagination').remove();
<% end %>