config/routes.rb
InvestBrasil::Application.routes.draw do
  root :to => 'home#index'  
  
  # TO-DO
  # ALTERAR NO DEVELOPERS.FACEBOOK.COM 
  # A ROTA DE LOCALHOST:3000 QUANDO SISTEMA FOR PRO AR

  match 'auth/:provider/callback', to: 'sessions#create_with_facebook'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :companies

  match 'companies/:company_id/create_comment', to: 'companies#create_comment', as: 'create_comment'
  match 'companies/:company_id/:comment_id/create_subcomment', to: 'companies#create_subcomment', as: 'create_subcomment'
  match 'companies/:company_id/:comment_id/create_subcomment_in_notifications', to: 'companies#create_subcomment_in_notifications', 
                                                                      as: 'create_subcomment_in_notifications'
  match 'companies/:company_id/:comment_id/create_subcomment_in_home', to: 'companies#create_subcomment_in_home', 
                                                                      as: 'create_subcomment_in_home'
                                                                    
  match 'companies/:company_id/follow_company', to: 'users#follow_company', as: 'follow_company'
  match 'companies/:company_id/unfollow_company', to: 'users#unfollow_company', as: 'unfollow_company'

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'  
  
  resources :users
  resources :sessions
  resources :notifications

  match "/companies_ajax" => "companies#companies_ajax"
  match "/redirect_to_correct_company" => "companies#redirect_to_correct_company",
                                :as => 'redirect_to_correct_company'

  match "companies/sector/:sector_id" => "sectors#show", :as => 'sectors'                         
  match "companies/subsector/:subsector_id" => "subsectors#show", :as => 'subsectors'                         
  match "companies/segment/:segment_id" => "segments#show", :as => 'segments'                         

end

app/models/comment.rb
#encoding: utf-8

class Comment < ActiveRecord::Base
	belongs_to :company_users
	has_many :subcomments
	belongs_to :user

	def owner
		user = User.find self.user_id
		if user
			user.name
		else
			'Usuário não existe mais'
		end
	end
end

app/models/company.rb
class Company < ActiveRecord::Base
	attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "150x150>", :thumb => "32x32>" }
	has_many :company_users
	belongs_to :segment
	belongs_to :sector
	belongs_to :subsector
end

app/models/company_user.rb
class CompanyUser < ActiveRecord::Base
	belongs_to :company
	belongs_to :user
	has_many :comments
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	belongs_to :user
end

app/models/sector.rb
class Sector < ActiveRecord::Base
	has_many :companies
end

app/models/segment.rb
class Segment < ActiveRecord::Base
	has_many :companies
end

app/models/subcomment.rb
#encoding: utf-8

class Subcomment < ActiveRecord::Base
	belongs_to :comment
	belongs_to :user

	def owner
		user = User.find self.user_id
		if user
			user.name
		else
			'Usuário não existe mais'
		end
	end
end

app/models/subsector.rb
class Subsector < ActiveRecord::Base
	has_many :companies
end

app/models/user.rb
require "open-uri"

class User < ActiveRecord::Base
	has_many :company_users
	has_many :subcomments
	has_many :comments
	has_many :notifications

	attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "32x32>" }

	attr_accessible :name, :email, :password, :admin
	attr_accessor :password

	before_save :encrypt_password

	def avatar_from_url(url)
    self.avatar = open(url)
  end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

	def admin?
		self.admin
	end

	def make_admin!
		self.update_attributes! :admin => true
	end

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def self.from_omniauth(auth)
	  user = User.find_by_provider_and_uid auth["provider"], auth["uid"]
	  if user.blank?
	  	create! do |user|
		    user.provider = auth.provider
	  	  user.uid = auth.uid
	      user.name = auth.info.name
	      user.email = auth.info.email
	      user.oauth_token = auth.credentials.token
	      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	      user.avatar_from_url auth.info.image
	  	end
	  else
	  	user.update_attributes( 
	  		:provider => auth.provider,
	  	  :uid => auth.uid, 
	  	  :name => auth.info.name,
	      :oauth_token => auth.credentials.token,
	      :oauth_expires_at => Time.at(auth.credentials.expires_at)
	    )
	    user.avatar_from_url auth.info.image
	    user.save
	    user
	  end
	end

	def is_following_company? company_id
		company_user = CompanyUser.where(:user_id => self.id, 
																		 :company_id => company_id, 
																		 :follow => true).first
		not company_user.blank?
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
	  	company_user = CompanyUser.where(:user_id => current_user.id, :follow => true)
	  	if company_user.blank?
	  		@comments = []
			else
				@comments = company_comments(company_user)
	  	end
	  end
  end

  private

  def company_comments company_user
  	companies_ids = []
  	company_user.each do |c|
  		companies_ids << c.company_id
  	end

  	companies_users = []
  	companies_ids.each do |company_id|
			company_user = CompanyUser.where(:company_id => company_id, :user_id => current_user.id)
			companies_users << company_user
		end

		comments = []

		companies_users.each do |company_user|
			company_user.each do |c|	
				c.comments.each do |comment|
					comments << comment unless comments.include? comment
				end
			end
		end

		if comments.blank?
			[]
		else
			comments.sort_by{|c| c[:updated_at]}.reverse
		end
	end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController

	def show
		@sector = Sector.find params[:sector_id]
		@companies = Company.where(:sector_id => params[:sector_id])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new params[:user]
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@user = User.find params[:id]
	end

	def update
		@user = User.find params[:id]
		
		if @user.update_attributes params[:user]
			redirect_to edit_user_path(@user), :notice => 'Atualizado com sucesso'			
		else
			render 'edit'
		end
	end

	def follow_company
		CompanyUser.create :user_id => session[:user_id],
											 :company_id => params[:company_id],
											 :follow => true
		redirect_to company_path params[:company_id]	 									 
	end

	def unfollow_company
		company_user = CompanyUser.where(:user_id => session[:user_id],
																:company_id => params[:company_id],
																:follow => true).first
		company_user.update_attributes :follow => nil

		redirect_to company_path params[:company_id]
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
#encoding: utf-8

module CommentsHelper
	def placeholder_condition user
		if user
			'Entre com seu comentário'
		else
			'Cadastre-se para poder comentar'
		end
	end

	def disabled? user
		if user
			''
		else
			'disabled'
		end
	end

	def disabled_if_no_user user
		if user
			false
		else
			true
		end
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/helpers/subsectors_helper.rb
module SubsectorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvestBrasil</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "companies" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">InvestBrasil</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Notificações", notifications_path %></li>
          </ul>
          <ul class="nav">
            <li><%= link_to "Empresas", companies_path %></li>
          </ul>

          <%= form_tag(redirect_to_correct_company_path, :class => 'navbar-search pull-left') do %>
            <%= text_field_tag :company, '', :class => "search-query span2", :placeholder => 'Procurar empresas'%>
           <% end %> 

          <div class="btn-group pull-right">
            <% if current_user %>
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="icon-user"></i> <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Editar", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sair", signout_path, id: "sign_out" %></li>
              </ul>
            <% else %>
                <b><%= link_to "Login", log_in_path, :class => 'btn' %></b>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
    </div>
  </div>
</body>
</html>  